apps sc: add oidc integration to harbor

diff --git a/helmfile/charts/init-harbor/templates/init-harbor-cm.yml b/helmfile/charts/init-harbor/templates/init-harbor-cm.yml
--- a/helmfile/charts/init-harbor/templates/init-harbor-cm.yml
+++ b/helmfile/charts/init-harbor/templates/init-harbor-cm.yml
@@ -9,21 +9,21 @@ data:
 
     echo "testing curl address {{ .Values.endpoint }}"
     # Set up initial state for harbor.
-    EXISTS=$(curl -k -u admin:Harbor12345 {{ .Values.endpoint }}/projects/1 | jq '.code') || {
+    exists=$(curl -k -u admin:Harbor12345 {{ .Values.endpoint }}/projects/1 | jq '.code') || {
       echo "ERROR L.${LINENO} - Harbor url {{ .Values.endpoint }}/projects/1 cannot be reached."
       exit 1
     }
-    if [ -z "$EXISTS" ] 
+    if [ -z "$exists" ] 
     then
       echo "ERROR - Harbor url {{ .Values.endpoint }}/projects/1 did not return any code (probably canot be reached)"
       exit 1
     fi
     echo "Setting up initial harbor state"
-    if [ "$EXISTS" != "404" ]
+    if [ "$exists" != "404" ]
     then
-        NAME=$(curl -k -X GET -u admin:Harbor12345 {{ .Values.endpoint }}/projects/1 | jq '.name')
+        name=$(curl -k -X GET -u admin:Harbor12345 {{ .Values.endpoint }}/projects/1 | jq '.name')
 
-        if [ "$NAME" == "\"library\"" ]
+        if [ "$name" == "\"library\"" ]
         then
             # Deletes the default project "library"
             echo Removing project library from harbor
@@ -42,8 +42,28 @@ data:
                     "auto_scan": "true"
                 }
             }'
-            echo "Harbor initialized"
+            echo "Private default project created"
         fi
-    else
-        echo "Harbor was already initilized"
-    fi
+      else
+        echo "Harbor already created default project"
+      fi
+      echo "Configuring oidc support"
+      err=$(curl -k -X PUT "{{ .Values.endpoint }}/configurations" \
+        -u admin:{{ .Values.password }} \
+        -H "accept: application/json" \
+        -H "Content-Type: application/json" \
+        -d "{ \"oidc_verify_cert\": {{ .Values.oidc.verifyCert }}, 
+              \"auth_mode\": \"oidc_auth\", 
+              \"self_registration\": false,
+              \"oidc_scope\": \"{{ .Values.oidc.scope }}\", 
+              \"oidc_name\": \"dex\", 
+              \"oidc_client_id\": \"harbor\", 
+              \"oidc_endpoint\": \"{{ .Values.oidc.endpoint }}\",
+              \"oidc_client_secret\": \"{{ .Values.oidc.clientSecret }}\"}")
+
+      if [ -n "$err" ]
+      then
+        echo "ERROR when configuring oidc: $err"
+        exit 1
+      fi      
+      echo "Harbor initialized"
